### ISSUE TITLE
plone.app.stagingbehavior not needed for Plone 4

### ISSUE THREAD

**Issue by david-batranu** [plone/plone.app.iterate#51]
I'm adding issue here as `plone.app.stagingbehavior` seems to be abandoned. From my experience it appears that it is no longer required as `plone.app.iterate>=3.1.0` functions perfectly with Plone 4. 

---

There are two packages involved in providing check-in/checkout functionality to Dexterity content types, for Plone 4:

* plone.app.iterate
* plone.app.stagingbehavior

The first package handles Archetypes support while the second is a compatibility wrapper over the first, extending the functionality to Dexterity types.
The interaction between the two is not very well documented. The "stagingbehavior" package states that it is needed on Plone 4 while Plone 5 only needs the "iterate" package.
Unfortunately the functionality provided by "stagingbehavior" is not complete, it has the following issues:

* no integration with Diazo themes
* no support for "View differences" (between the working copy and original)
* it breaks the builtin Dexterity support in newer "plone.app.iterate" versions

Newer versions of "plone.app.iterate" (>=3.1.0) have implemented the required functionality for Dexterity types, fixing the above issues; so "stagingbehavior" is no longer required.
In fact (as previously stated), it actively breaks the builtin "iterate". These are things that are not made clear in the documentation and has taken a lot of trial, error and debugging
across both Plone 4 and 5 with different versions of the "iterate" package.

**Comment by gforcada** [comment]
@david-batranu I see that there is an error message being shown if p.a.stagingbehavior is installed: https://github.com/plone/plone.app.iterate/blob/fe49bc33a0f0b38fe9d762c63c507f592ff85d9a/plone/app/iterate/__init__.py#L44 you can thank @vangheem for that.

Which kind of documentation do you think should be improved? The one provided on the README, or on the global Plone documentation? :thinking: 

On the later there is only one hit on the current docs: https://github.com/plone/documentation/search?utf8=%E2%9C%93&q=stagingbehavior&type= but it is already talking about how replacing it.

**Comment by gforcada** [comment]
I updated buildout.coredev branches 5.0, 5.1 and 5.2 to remove any reference to plone.app.stagingbehavior, as all of them use plone.app.iterate +3.1.0 it does not make sense to recommend as part of the ecosystem a package that will break that ecosystem :smile:
