### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jensens** [plone/plone.app.iterate#57]
Dear @plone/release-team - may we have a release? The latest bug fix is really import for users of p.a.iterate! Thanks!

**Comment by mauritsvanrees** [comment]
I have released 3.3.6 and have added that to the coredev 5.1  and 5.2 buildouts.
Are earlier Plones affected?

Strange is that 5.0 coredev pins iterate to 3.2.4, but sources.cfg lists branch 2.2.x. Oh, when I checkout that branch, I do get version 3.2.4 as latest release. So it looks like the branch was misnamed.
@jensens you did that last year, in plone/buildout.coredev@e9e7fc3b69ad7fbd338d55d385b9442054efce2a. Can you check? I guess the branch simply needs to be renamed.

**Comment by jensens** [comment]
ok, done. sorry for the confusion. thanks for the release!
